### ISSUE TITLE
empty param of timestamp

### ISSUE THREAD

**Issue by zyairelai** [bybit-exchange/docs#211]
**Bug Description**
Last night I was running my bybit bot on Python without running into issue at all.  
However this morning when I woke up, this line that exactly from [test.py](https://github.com/bybit-exchange/api-connectors/blob/master/official-http/python/test.py) is running into problem

**Screenshots**
I am running this line. 
```
print(client.LinearPositions.LinearPositions_myPosition(symbol="BTCUSDT").result())
```
This is what I get
```
({'ret_code': 10001, 'ret_msg': 'empty param of timestamp', 'ext_code': '', 'ext_info': '', 'result': None, 'time_now': '1622783415.711586'}, <bravado.requests_client.RequestsResponseAdapter object at 0x7f6f791203a0>)
```

**Browser (please complete the following information):**
 - OS: Ubuntu 20.04 LTS, running on Terminal

**Last upstream Slate commit (run `git log --author="Robert Lord" | head -n 1`):**
There is no output from here

**Comment by Kvg87** [comment]
Hey,

How did you fix this, im running into the same error..

Thnks!
