### ISSUE TITLE
Missing enum units for kline interval in English marketdata api

### ISSUE THREAD

**Issue by Al153** [bybit-exchange/docs#234]
Hi,

In the documentation for the `GET /v2/public/kline/list` endpoint, the definition for the parameter 

Interval | true | string | Data refresh interval. Enum : 1 3 5 15 30 60 120 240 360 720 "D" "M" "W"
-- | -- | -- | --

is missing units for the numerical values.

Do 1,3,5,15,..720 refer to minutes or seconds?

Thanks,

Al

**Comment by dextertd** [comment]
<img width="377" alt="Screenshot 2021-06-28 at 17 33 34" src="https://user-images.githubusercontent.com/54495183/123672199-f8dd0500-d836-11eb-9a02-adf040c20e55.png">

The API `interval` ENUMs are the same as what is available on the website, although all ints are in minutes (`60` -> 1 hour kline).

I think the docs could be improved slightly on this, will try to add some clarification.

Hope this helps.
