### ISSUE TITLE
Rest API response for "User Trade Records" always returns 40002

### ISSUE THREAD

**Issue by steilx** [bybit-exchange/docs#53]
This happens both in prod API and testnet since today. The exact same API calls returned the data as expected until today.

GET /v2/private/execution/list
```
{
  ret_code: 40002,
  ret_msg: 'Error response',
  ext_code: '',
  ext_info: '',
  result: null,
  time_now: '1588163668.992583',
  rate_limit_status: 119,
  rate_limit_reset_ms: 1588163668971,
  rate_limit: 120
}
```

**Comment by keyganker** [comment]
Thanks for your feedback!
It's a bug issued by today's release, and it' fixed
