### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by ddhb89** [bybit-exchange/docs#60]
My Trading Bot works like a charm for the last few days But now i got this Error Message on Testnet
{'result': None, 'ret_msg': 'invalid api_key', 'time_now': '1589962849.789200', 'ext_info': None, 'ret_code': 10003, 'ext_code': ''}

Why is my Key suddenly invalid?
I also created a new one and testet it again. But same Issue. I changed nothing on my Code. This error comes overnight.

**Comment by ddhb89** [comment]
After the 5th attempt. The new API Keys are working

**Comment by keyganker** [comment]
Please check whether your apikey is expired
